before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yqq bc pure-ftpd
  - sudo groupadd ftp
  - sudo useradd -s /bin/false -d /home/ftp -m -c "anonymous ftp" -g ftp ftp
  - sudo rm /etc/pure-ftpd/conf/NoAnonymous
  - echo "no" | sudo tee -a /etc/pure-ftpd/conf/NoAnonymous
  - cat /etc/pure-ftpd/conf/NoAnonymous
  - echo "bar" | sudo tee -a /home/ftp/foo.txt
  - sudo /etc/init.d/pure-ftpd restart
  - npm -g install jslint

language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.10
